plugins:
  - import
parser: "babel-eslint"

rules:
  no-unused-vars: "error"
  no-console: "error"
  quotes:
    - "error"
    - "double"
  eqeqeq: "error"
  no-unneeded-ternary: "error"
  nonblock-statement-body-position:
    - "error"
    - "beside"
  no-confusing-arrow: "error"
  no-var: "error"
  object-curly-spacing:
    - "error"
    - "always"
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/no-unresolved:
    - 2
    -
      caseSensitive: false
  key-spacing:
    - 2
    -
      singleLine:
        beforeColon: false
        afterColon: true
      multiLine:
        beforeColon: false
        afterColon: true
        align: "colon"



