export const EAT_CATEGORY="EAT_CATEGORY";
export const SHOP_CATEGORY="SHOP_CATEGORY";
export const NIGHTLIFE_CATEGORY="NIGHTLIFE_CATEGORY";
export const OUT_AND_ABOUT_CATEGORY="OUT_AND_ABOUT_CATEGORY";
export const SNACKS_AND_COFFEE="SNACKS_AND_COFFEE";
export const PHOTO_OP="PHOTO_OP";
