export const EAT_CATEGORY="EAT_CATEGORY";
export const SHOP_CATEGORY="SHOP_CATEGORY";
export const NIGHTLIFE_CATEGORY="NIGHTLIFE_CATEGORY";
export const OUT_AND_ABOUT_CATEGORY="OUT_AND_ABOUT_CATEGORY";
export const OUTDOORS_CATEGORY="OUTDOORS_CATEGORY";
export const COFFEE_AND_SNACKS_CATEGORY="COFFEE_AND_SNACKS_CATEGORY";
export const PHOTO_OP_CATEGORY="PHOTO_OP_CATEGORY";
